# -*- coding: utf-8 -*-

#       Z.        .            .                        MMM.    MMM.
#        MM7.     MMMMMMMMMMMMMMMM              7I      MM      MM      M+.
#         MMM     MM.          +M.              +M8~~~~~MM~~~~~~MM:~~~~+MM.
#           .     MM.          +M.              :MO     MM      MM     ~MI
#             N.  MM.          +M,              ,MO     MM      MM     ~M$
#    MN.     Z    MMMMMMMMMMMMMMM~              :MO     MM      MM     ~MZ
#     MMM    M    = .          ,   .            ~MO     MM      MM     ~M8.
#      MM8  8. M,                  MM           +MMMMMMMMMMMMMMMMMMMMMMMMM
#      .M.  M. MM     M+    MM.    MM.          :.                      $M.
#          M~  MM     M+    MM     MM           +MMMMMMMMMMMMMMMMMMMMMMMMMMM
#         .M.  MM     M+    MM     MM           ~MO
#         MI.  MMNNNNNMNNNNNMMDNNNNMM           :MO                 8MM .
#        =M.   MM.                 MZ.          :MO  Z...................
#       .MM                    M8               :MO                      NMD
#    DMMMM      =MONZ$$$$$$$$$MMMM.             ZMD$$$ZMD$$$M$$$$$$$$$$$$$$$$:
#      =MM          ,M       MMZ                MM.   ,MO    M+.      MM:
#      :MM.           MD   MMM.                .MM    ,MO     ~M..  .MM,.
#      MMM             $MMMM.                  MM .   ,MO       MM MM .
#      MMM            .MMMMM8                 MM.     ,MO     :.  MMM..
#      MMM.      . =MM8.    DMMMMN+.         MM.      7MDMMM8.      MMMMM8:  .
#        .    +MMM~  .        .:MMMMMO.     M.        MMM?             7MMMMD.
#          .                         .    .                                ..
#
#                                                 Generated by glassgiant.com

"""
Mannou Manga Downloader
=======================

Mannou is a manga downloader, written in Python, for downloading manga
from various sites. Basic usage::

    >>> import mannou
    >>> manga = mannou.get('https://www.mangatown.com/manga/girls_panzer/')
    >>> manga.title
    'Girls & Panzer'
    >>> manga.chapters
    [ChapterType('1', 'https://www.mangatown.com/manga/girls_panzer/c001/'],
     ...,
    ChapterType('21', 'https://www.mangatown.com/manga/girls_panzer/c021/')]
    >>> len(manga)
    21
    >>> manga.download() # download all manga and save it to default location
    >>> manga.download(start='1', end='1') # Download only chapter 1
    >>> manga.download(start='1', end='3') # Download only chapter 1 to 3


The other methods and properties are supported. Full documentation
is at <https://mannou.readthedocs.io>.

"""


from .mannou import Mannou
from .api import info, get, download
