# -*- coding: utf-8 -*-

#       Z.        .            .                        MMM.    MMM.
#        MM7.     MMMMMMMMMMMMMMMM              7I      MM      MM      M+.
#         MMM     MM.          +M.              +M8~~~~~MM~~~~~~MM:~~~~+MM.
#           .     MM.          +M.              :MO     MM      MM     ~MI
#             N.  MM.          +M,              ,MO     MM      MM     ~M$
#    MN.     Z    MMMMMMMMMMMMMMM~              :MO     MM      MM     ~MZ
#     MMM    M    = .          ,   .            ~MO     MM      MM     ~M8.
#      MM8  8. M,                  MM           +MMMMMMMMMMMMMMMMMMMMMMMMM
#      .M.  M. MM     M+    MM.    MM.          :.                      $M.
#          M~  MM     M+    MM     MM           +MMMMMMMMMMMMMMMMMMMMMMMMMMM
#         .M.  MM     M+    MM     MM           ~MO
#         MI.  MMNNNNNMNNNNNMMDNNNNMM           :MO                 8MM .
#        =M.   MM.                 MZ.          :MO  Z...................
#       .MM                    M8               :MO                      NMD
#    DMMMM      =MONZ$$$$$$$$$MMMM.             ZMD$$$ZMD$$$M$$$$$$$$$$$$$$$$:
#      =MM          ,M       MMZ                MM.   ,MO    M+.      MM:
#      :MM.           MD   MMM.                .MM    ,MO     ~M..  .MM,.
#      MMM             $MMMM.                  MM .   ,MO       MM MM .
#      MMM            .MMMMM8                 MM.     ,MO     :.  MMM..
#      MMM.      . =MM8.    DMMMMN+.         MM.      7MDMMM8.      MMMMM8:  .
#        .    +MMM~  .        .:MMMMMO.     M.        MMM?             7MMMMD.
#          .                         .    .                                ..
#
#                                                 Generated by glassgiant.com

"""
Mannou Manga Downloader
=======================

Mannou is a manga downloader  for downloading manga
from various sites. Basic usage::

    >>> import mannou
    >>> url = 'https://manganelo.com/manga/aiura'
    >>> manga = mannou.get(url)
    >>> str(manga) # or manga.title
    Aiura
    >>> manga[0] # or manga.chapters[0]
    Chapter(number='1', url='https://manganelo.com/chapter/aiura/chapter_1')
    >>> images = manga.get_chapter_images(manga[0].url)
    >>> images[0]
    Image(name='1.jpg', url='http://s8.mkklcdn.com/mangakakalot/a1/aiura/chapter_1/1.jpg')
    >>> mannou.download(url, start=1, end=5) # Download every chapters 1 until 5 in 'Aiura' and save it to default location (~/Manga or %USERPROFILE%\Manga)


The other methods and properties are supported. Full documentation
is at <https://mannou.readthedocs.io>.

"""


from .anilist import AniList
from .api import download, get, info
from .mannou import Mannou
